### ISSUE TITLE
init() on Swift 4.0

### ISSUE THREAD

**Issue by ba1ashov** [TangentW/PhotosSheet#1]
hi
I used this library on Xcode 8.3 and swift 3.0 and all work normally.
But, after update i get error in PhotosSheet.swift file.
On 84 line with call         

> self.init(actions: actions, mediaOption: mediaOption, displayedPhotosLimit: displayedPhotosLimit, selectedPhotosLimit: selectedPhotosLimit, options: options) { didSelectedAssets($0.0) }

how fix i can fix it?

**Comment by ba1ashov** [comment]
It seems that I fixed it

>         self.init(actions: actions, mediaOption: mediaOption, displayedPhotosLimit: displayedPhotosLimit, selectedPhotosLimit: selectedPhotosLimit, options: options) { (a, s) in
>             didSelectedAssets(a)
>         }

Now it working

**Comment by TangentW** [comment]
@Balashov152 

It's an evolution of Swift 4.
See:
[SE-0110 Distinguish between single-tuple and multiple-argument function types](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md)
